name: Minitalk CI

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make valgrind

    - name: Check Norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette
        norminette src/ include/ libft/ gc_collector/

    - name: Build Project
      run: make

    - name: Run Debug Build
      run: |
        make fclean
        make BUILD=debug

    - name: Run Memory Check Build
      run: |
        make fclean
        make BUILD=valgrind

    - name: Test Basic Functionality
      run: |
        ./bin/server & SERVER_PID=$!
        sleep 1
        ./bin/client $SERVER_PID "Hello, World!"
        kill $SERVER_PID

    - name: Cleanup
      run: make fclean

  bonus:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Build Bonus
      run: |
        make
        make clean

    - name: Test Bonus Features
      run: |
        ./bin/server & SERVER_PID=$!
        sleep 1
        ./bin/client $SERVER_PID "Test with 🌟 Unicode"
        ./bin/client $SERVER_PID "Multiple clients test 1";./bin/client $SERVER_PID "Multiple clients test 2"
        kill $SERVER_PID
